### ISSUE TITLE
Pop

### ISSUE THREAD

**Issue by luanuti** [dilp90/InteligenciaArtificial_y_RedesNeuronales_UANL_FIME#6]
Hola

**Comment by vvazquezv** [comment]
Estás en la clase de IA y RN?


Obtener Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
From: luanuti ***@***.***>
Sent: Saturday, May 4, 2024 12:08:07 PM
To: dilp90/InteligenciaArtificial_y_RedesNeuronales_UANL_FIME ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dilp90/InteligenciaArtificial_y_RedesNeuronales_UANL_FIME] Pop (Issue #6)


Hola
